services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dim_reduction
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dim_reduction?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    networks:
      - app-network

  calculator:
    build:
      context: ./calculator  
      dockerfile: Dockerfile
    container_name: calculator
    ports:
      - "5000:5000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "7005:7005"
    depends_on:
      - backend
      - calculator
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge